<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
	<Version>1.0.3</Version>
	<AssemblyVersion>1.0.3.0</AssemblyVersion>
	<FileVersion>1.0.3.0</FileVersion>
	<Product>DisplayModeSwitcher</Product>
	<Description>Tool zur dynamischen Auflösungsumschaltung basierend auf aktiven Profilen.</Description>
	<RepositoryUrl>https://github.com/WhiskyGuerra/DisplayModeSwitcher</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DisplayModeSwitcher.Tests" />
  </ItemGroup>


</Project>
